### ISSUE TITLE
build with lua-cjson 2.1.0-1 fails for luajit 2.1

### ISSUE THREAD

**Issue by akornatskyy** [JakobGreen/lua-requests#24]
## Steps to Reproduce

```sh
docker run -it --rm akorn/luarocks:luajit2.1-alpine sh
apk add unzip gcc libc-dev g++ openssl-dev

luarocks install lua-requests
```

Error:

```log
lua-requests 1.2-1 depends on lua-cjson 2.1.0-1 (not installed)
Installing https://luarocks.org/lua-cjson-2.1.0-1.src.rock

gcc -O2 -fPIC -I/usr/local/include -c lua_cjson.c -o lua_cjson.o
lua_cjson.c:1298:13: error: static declaration of 'luaL_setfuncs' follows non-static declaration
 static void luaL_setfuncs (lua_State *l, const luaL_Reg *reg, int nup)
             ^~~~~~~~~~~~~
In file included from lua_cjson.c:44:0:
/usr/local/include/lauxlib.h:88:18: note: previous declaration of 'luaL_setfuncs' was here
 LUALIB_API void (luaL_setfuncs) (lua_State *L, const luaL_Reg *l, int nup);
                  ^~~~~~~~~~~~~
In file included from lua_cjson.c:47:0:
fpconv.h:15:20: warning: inline function 'fpconv_init' declared but never defined
 extern inline void fpconv_init();
                    ^~~~~~~~~~~

Error: Failed installing dependency: https://luarocks.org/lua-cjson-2.1.0-1.src.rock - Build error: Failed compiling object lua_cjson.o
```

## Workaround

The following works:
```
luarocks install lua-requests 1.2-0
```

**Comment by kenhys** [comment]
@akornatskyy @JakobGreen 

The build failure issue seems fixed in lua-cjson 2.1.0.6-1, so lua-requests dependency to lua-cjson should be `"lua-cjson == 2.1.0-1"`.

lua-requests depends to lua-cjson ***2.1.0-1***, it fails.

```
kenhys@c54d03208bdc:/lua/work$ luarocks install lua-requests
Installing https://luarocks.org/lua-requests-1.2-1.src.rock
Missing dependencies for lua-requests 1.2-1:
   lua-cjson == 2.1.0-1 (2.1.0.6-1 installed)

lua-requests 1.2-1 depends on lua-cjson == 2.1.0-1 (2.1.0.6-1 installed)
Installing https://luarocks.org/lua-cjson-2.1.0-1.src.rock
gcc -O2 -fPIC -I/home/kenhys/.luaenv/versions/luajit-2.1.0-beta3/include/luajit-2.1 -c lua_cjson.c -o lua_cjson.o
lua_cjson.c:1298:13: error: static declaration of 'luaL_setfuncs' follows non-static declaration
 static void luaL_setfuncs (lua_State *l, const luaL_Reg *reg, int nup)
             ^~~~~~~~~~~~~
In file included from lua_cjson.c:44:
/home/kenhys/.luaenv/versions/luajit-2.1.0-beta3/include/luajit-2.1/lauxlib.h:88:18: note: previous declaration of 'luaL_setfuncs' was here
 LUALIB_API void (luaL_setfuncs) (lua_State *L, const luaL_Reg *l, int nup);
                  ^~~~~~~~~~~~~
In file included from lua_cjson.c:47:
fpconv.h:15:20: warning: inline function 'fpconv_init' declared but never defined
 extern inline void fpconv_init();
                    ^~~~~~~~~~~

Error: Failed installing dependency: https://luarocks.org/lua-cjson-2.1.0-1.src.rock - Build error: Failed compiling object lua_cjson.o
```

But, lua-cjson doesn't fail. ( ***2.1.0.6-1*** )

```
kenhys@c54d03208bdc:/lua/work$ luarocks install lua-cjson   
Installing https://luarocks.org/lua-cjson-2.1.0.6-1.src.rock
gcc -O2 -fPIC -I/home/kenhys/.luaenv/versions/luajit-2.1.0-beta3/include/luajit-2.1 -c lua_cjson.c -o lua_cjson.o
gcc -O2 -fPIC -I/home/kenhys/.luaenv/versions/luajit-2.1.0-beta3/include/luajit-2.1 -c strbuf.c -o strbuf.o
gcc -O2 -fPIC -I/home/kenhys/.luaenv/versions/luajit-2.1.0-beta3/include/luajit-2.1 -c fpconv.c -o fpconv.o
gcc -shared -o cjson.so -L/home/kenhys/.luaenv/versions/luajit-2.1.0-beta3/lib lua_cjson.o strbuf.o fpconv.o
lua-cjson 2.1.0.6-1 is now installed in /home/kenhys/.luaenv/versions/luajit-2.1.0-beta3 (license: MIT)

```

**Comment by akornatskyy** [comment]
Thanks, @kenhys. The following `lua-requests-1.2-1.rockspec` uses the latest version of `lua-cjson`.

```sh
https://gist.githubusercontent.com/akornatskyy/6a6ed81ae30e705c1f339f82e5c41397/raw/64ef319b56f08a432e01969503024c26558ca4c2/lua-requests-1.2-1.rockspec
```

**Comment by JakobGreen** [comment]
Updated to latest cjson in 1.2-2
